# 应用名称
spring:
  application:
    name: news
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  web:
    resources:
      static-locations: classpath:/static/,classpath:/bg
  profiles:
    active: pro
mybatis-plus:
  global-config:
    db-config:
      id-type: auto

server:
  port: 80

