# 应用名称
spring:
  application:
    name: news
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      url: jdbc:mysql://8.130.96.252:3306/yr
server:
  port: 80

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
